### ISSUE TITLE
Template Design Review - Email 1

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#11]
@codextiny 

1. Please decrease spacing here where the arrows are.
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/a2ef8d56-a54b-4a99-8332-8d9d7da7c9d8)

2. Button on mobile looks too large but the Litmus mobile preview does not look like that. Should we cut down on the text? 
![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/e8e06a13-27b3-4b4c-ba63-7da084d3636d)![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/9730ca96-d06e-4304-89b4-a5fc3f7aa9fd)
3. Please remove periods from subject line and preview text to be consistent with google doc.![image](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/ea66f203-6b88-4ace-809d-37c7a83b593f)
4. Is it possible SendGrid mobile view isn’t correct? Here is my mobile view and it looks fine. 

![IMG_3813](https://github.com/shannonbaldwin/Litmus-SG-Project/assets/167017886/78e170d4-0e41-4708-bec5-7cf1f5bd892b)

**Comment by codextiny** [comment]
@shannonbaldwin 

1. Please decrease spacing here where the arrows are.
Answer: Adjusted spacing.

2. Button on mobile looks too large but the Litmus mobile preview does not look like that. Should we cut down on the text?
Asnwer:  Every device/platform have different previews, on some devices button text might be going on second line because in some of template your buttons have 5 to 6 words, so our suggestion is to reduce button's text to 2 to 3 words.

3. Please remove periods from subject line and preview text to be consistent with google doc.
Answer: Done from our side.

4. Is it possible SendGrid mobile view isn’t correct? Here is my mobile view and it looks fine.
Answer: As i mentioned above that every device and platform have different previews, it might be 'sendgrid' mobile preview problem like you remember the footer issue on litmus preview in all templates that we had explained you its litmus's fault, same thing happening here, Please check on real devices or email clients like litmus provided . Hope you got our point if you still have any question, let us know.

Thanks,
Codextiny
