### ISSUE TITLE
New Footer Signature Block:Template ID: d-afd97d3a77384a68bf05700e6aecb503 

### ISSUE THREAD

**Issue by shannonbaldwin** [shannonbaldwin/Litmus-SG-Project#41]
@codextiny I adjusted the max-height to 64px to make the images a full circle. They render properly in the template preview in SG but when I send a test to myself, they do not. 
![image](https://github.com/user-attachments/assets/7db7cc4e-779b-4fff-ad68-932e7e3749ca)![image](https://github.com/user-attachments/assets/91f14ba5-4284-4d5d-a65d-29df15dcd36f)

**Comment by codextiny** [comment]
@shannonbaldwin 

That's why we suggest you to make/crop images in exact height/width because some email clients doesn't support max-width, max-height, height, width, border-radius.
suppose you made design where image height width is 94x94 and its rounded in figma, then export it as it is in same resolution with rounded corners .

Hope you got our point

Thanks
